apiVersion: v1
kind: ReplicationController
metadata:
  name: security-ms
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: security-ms
    spec:
      containers:
      - name: security-ms
        image: node
        workingDir: /opt/node-app
        command: ["/opt/node-app/docker-entrypoints.sh"]
        env:
        - name: URL
          value: "yodeling-aardwolf-mongodb"
        ports:
        - containerPort: 3001
          name: http
        volumeMounts:
        - mountPath: /opt/node-app/
          name: node-app
          subPath: "greenlab/01-Microservices/01-security_microservice"
      volumes:
        - name: node-app
          gitRepo:
            repository: "https://github.com/t5unamie/greenlab.git"
            revision: "715d6cbbff80519194a70bb7ec1e712f645d3f30"