apiVersion: v1
kind: Service
metadata:
  name: securitysvc
  labels:
    app: security-ms
spec:
  ports:
  - port: 3001
    protocol: TCP
    name: http
    targetPort: 3001
  selector:
    app: security-ms
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: security-ms
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: security-ms
    spec:
      containers:
      - name: security-ms
        image: node
        workingDir: /opt/node-app
        command: ["/opt/node-app/docker-entrypoints.sh"]
        env:
        - name: URL
          value: "security-db-mongodb.default.svc.cluster.local"
        ports:
        - containerPort: 3001
          name: http
        volumeMounts:
        - mountPath: /opt/node-app/
          name: node-app
          subPath: "greenlab/01-Microservices/01-security_microservice"
      volumes:
        - name: node-app
          gitRepo:
            repository: "https://github.com/t5unamie/greenlab.git"
            revision: "02ffd9a45638a37164115a93f978a4d6e47707c6"